default:
  name: "pipeline_name"
  base_path: "/app"
  feed_file: "@format {this.base_path}/labnotes/settings/{this.name}/feeds.yaml"
  keywords_file: "@format {this.base_path}/labnotes/settings/{this.name}/keywords.json"